const snarkjs = require('snarkjs');
const { buildPoseidon } = require('circomlibjs');
import * as fs from 'fs';
import * as path from 'path';
import { v4 as uuidv4 } from 'uuid';
import type { BadgeType } from './employeeDirectory';

/**
 * ZK-Proof Service
 * 
 * Handles zero-knowledge proof verification for Corporate Excellence 2025
 * NFT ownership authentication. Provides privacy-preserving verification
 * without revealing user identities or wallet addresses.
 */

export class ZKProofService {
    private verificationKey: any;
    private readonly CORPORATE_EXCELLENCE_CONTRACT = '0x742d35Cc6634C0532925a3b8D8B5d3d8c0eF7e95';
    private isEnabled: boolean = false;

    constructor() {
        this.loadVerificationKey();
    }

    /**
     * Load the verification key from the circuits workspace
     */
    private loadVerificationKey(): void {
        try {
            const vkeyPath = path.join(__dirname, '..', 'zkp', 'verification_key.json');
            
            if (!fs.existsSync(vkeyPath)) {
                console.log('⚠️  ZK-proof verification key not found - running in demo mode');
                console.log(`   - Missing file: ${vkeyPath}`);
                console.log('   - ZK-proof features will be disabled');
                this.isEnabled = false;
                return;
            }

            this.verificationKey = JSON.parse(fs.readFileSync(vkeyPath, 'utf8'));
            // The circuit (nftOwnership.circom) exposes ~19 public signals.
            // If nPublic is 4 the key is a placeholder — regenerate after running:
            //   cd circuits && npm install && npm run compile && npm run setup && npm run ceremony
            //   cp verification_key.json ../backend/src/zkp/verification_key.json
            if (this.verificationKey.nPublic < 10) {
                console.warn('⚠️  verification_key.json appears to be a placeholder (nPublic=' + this.verificationKey.nPublic + ').');
                console.warn('   Regenerate it by running the circuit setup — see circuits/README.md');
            }
            this.isEnabled = true;
            console.log('🔑 ZK-proof verification key loaded successfully');
            console.log(`   - Protocol: ${this.verificationKey.protocol}`);
            console.log(`   - Curve: ${this.verificationKey.curve}`);
            console.log(`   - Public inputs: ${this.verificationKey.nPublic}`);

        } catch (error) {
            console.error('💥 Failed to load verification key:', error);
            console.log('⚠️  ZK-proof service will run in demo mode');
            this.isEnabled = false;
        }
    }

    /**
     * Verify a zero-knowledge proof of NFT ownership
     * 
     * @param proof - The zk-SNARK proof generated by the mobile wallet
     * @param publicSignals - Public signals from the proof generation
     * @returns Promise<boolean> - True if the proof is valid
     */
    async verifyNFTOwnershipProof(proof: any, publicSignals: string[]): Promise<boolean> {
        try {
            // Check if ZK-proof service is enabled
            if (!this.isEnabled) {
                // SECURITY: Fail closed - if service is not properly configured, reject all proofs
                console.error('❌ ZK-proof service disabled - verification REJECTED (fail closed)');
                console.error('   Configure ZKP_VERIFICATION_KEY_PATH to enable proof verification');
                return false;
            }

            console.log('🔍 Starting ZK-proof verification process...');
            console.log('📊 Verification details:');
            console.log(`   - Public signals: ${publicSignals.length} values`);
            console.log(`   - Expected NFT contract: ${this.CORPORATE_EXCELLENCE_CONTRACT}`);

            // Validate proof structure
            if (!this.isValidProofStructure(proof)) {
                console.log('❌ Invalid proof structure');
                return false;
            }

            // Validate public signals
            if (!this.isValidPublicSignals(publicSignals)) {
                console.log('❌ Invalid public signals');
                return false;
            }

            // Log verification attempt (no sensitive data)
            console.log('🔐 Verifying ZK-proof with Groth16...');
            const startTime = Date.now();

            // Perform the actual zk-SNARK verification using SnarkJS
            const isValid = await snarkjs.groth16.verify(
                this.verificationKey,
                publicSignals,
                proof
            );

            const verificationTime = Date.now() - startTime;
            console.log(`⏱️  Groth16 verification completed in ${verificationTime}ms`);

            if (isValid) {
                console.log('✅ ZK-proof verification successful!');
                console.log('🎉 Privacy-preserving NFT ownership confirmed');
                console.log('🔒 User identity remains completely anonymous');
            } else {
                console.log('❌ ZK-proof verification failed');
                console.log('🚫 Invalid proof or user does not own required NFT');
            }

            return isValid;

        } catch (error) {
            console.error('💥 ZK-proof verification error:', error);
            console.log('🔍 Error details:');
            console.log(`   - Error type: ${error instanceof Error ? error.constructor.name : 'Unknown'}`);
            console.log(`   - Error message: ${error instanceof Error ? error.message : 'Unknown error'}`);
            
            return false;
        }
    }

    /**
     * Generate an authentication challenge for ZK-proof flow
     * 
     * @returns Object containing challenge data
     */
    generateAuthChallenge(): any {
        const challenge = {
            challengeId: uuidv4(),
            timestamp: Date.now(),
            nftContract: this.CORPORATE_EXCELLENCE_CONTRACT,
            requiredProof: 'NFT_OWNERSHIP',
            expiresAt: Date.now() + (5 * 60 * 1000), // 5 minutes expiry
            instructions: {
                step1: 'Generate ZK-proof using your mobile wallet',
                step2: 'Submit proof to /api/auth/verify-zkp endpoint',
                step3: 'Receive anonymous premium access token',
                privacy: 'Your wallet address will never be revealed'
            }
        };

        console.log(`🎯 Generated auth challenge: ${challenge.challengeId}`);
        console.log(`   - NFT Contract: ${challenge.nftContract}`);
        console.log(`   - Expires: ${new Date(challenge.expiresAt).toISOString()}`);

        return challenge;
    }

    /**
     * Validate the structure of a zk-SNARK proof
     * 
     * @param proof - Proof object to validate
     * @returns boolean - True if structure is valid
     */
    private isValidProofStructure(proof: any): boolean {
        if (!proof || typeof proof !== 'object') {
            console.log('❌ Proof is not an object');
            return false;
        }

        // Check for required Groth16 proof components
        const requiredComponents = ['pi_a', 'pi_b', 'pi_c'];
        
        for (const component of requiredComponents) {
            if (!proof[component]) {
                console.log(`❌ Missing proof component: ${component}`);
                return false;
            }

            if (!Array.isArray(proof[component])) {
                console.log(`❌ Proof component ${component} is not an array`);
                return false;
            }
        }

        // Validate pi_a (G1 point - 3 elements)
        if (proof.pi_a.length !== 3) {
            console.log('❌ Invalid pi_a length (expected 3 elements)');
            return false;
        }

        // Validate pi_b (G2 point - 3 elements, each with 2 sub-elements)
        if (proof.pi_b.length !== 3) {
            console.log('❌ Invalid pi_b length (expected 3 elements)');
            return false;
        }

        for (let i = 0; i < 2; i++) {
            if (!Array.isArray(proof.pi_b[i]) || proof.pi_b[i].length !== 2) {
                console.log(`❌ Invalid pi_b[${i}] structure`);
                return false;
            }
        }

        // Validate pi_c (G1 point - 3 elements)
        if (proof.pi_c.length !== 3) {
            console.log('❌ Invalid pi_c length (expected 3 elements)');
            return false;
        }

        console.log('✅ Proof structure validation passed');
        return true;
    }

    /**
     * Validate public signals from the proof
     * 
     * @param publicSignals - Array of public signals
     * @returns boolean - True if signals are valid
     */
    private isValidPublicSignals(publicSignals: string[]): boolean {
        if (!Array.isArray(publicSignals)) {
            console.log('❌ Public signals is not an array');
            return false;
        }

        if (publicSignals.length === 0) {
            console.log('❌ Public signals array is empty');
            return false;
        }

        // Validate that all signals are valid field elements (strings representing big integers)
        for (let i = 0; i < publicSignals.length; i++) {
            const signal = publicSignals[i];
            
            if (typeof signal !== 'string') {
                console.log(`❌ Public signal ${i} is not a string`);
                return false;
            }

            // Check if it's a valid numeric string
            if (!/^\d+$/.test(signal)) {
                console.log(`❌ Public signal ${i} is not a valid numeric string`);
                return false;
            }

            // Check for reasonable bounds (BN254 field size)
            try {
                const signalBigInt = BigInt(signal);
                const fieldSize = BigInt('21888242871839275222246405745257275088548364400416034343698204186575808495617');
                
                if (signalBigInt >= fieldSize) {
                    console.log(`❌ Public signal ${i} exceeds field size`);
                    return false;
                }
            } catch (error) {
                console.log(`❌ Public signal ${i} conversion to BigInt failed`);
                return false;
            }
        }

        console.log(`✅ Public signals validation passed (${publicSignals.length} signals)`);
        return true;
    }

    /**
     * Verify a Groth16 role proof from ZKRoleGate
     *
     * publicSignals layout (circom outputs come first, then public inputs in order):
     *   [0]      isValid             → output, must be "1"
     *   [1]      nftContractAddress  → roleHash (e.g. "1003" for admin)
     *   [2]      merkleRoot          → single-leaf tree root stored at registration
     *   [3..10]  merkleProof[0..7]   → all zeros for single-leaf tree
     *   [11..18] merkleIndices[0..7] → all zeros
     */
    async verifyRoleProof(
        proof: any,
        publicSignals: string[],
        expectedRoleHash: string,
        expectedMerkleRoot: string,
    ): Promise<{ valid: boolean; reason?: string }> {
        if (!this.isEnabled) {
            return { valid: false, reason: 'ZK-proof service not configured' };
        }
        if (!this.isValidProofStructure(proof)) {
            return { valid: false, reason: 'Invalid proof structure' };
        }
        if (!Array.isArray(publicSignals) || publicSignals.length !== 19) {
            return { valid: false, reason: `Expected 19 public signals, got ${publicSignals?.length}` };
        }
        if (publicSignals[0] !== '1') {
            return { valid: false, reason: 'Circuit output isValid is not 1' };
        }
        if (publicSignals[1] !== expectedRoleHash) {
            return { valid: false, reason: `Role hash mismatch: got ${publicSignals[1]}, expected ${expectedRoleHash}` };
        }
        if (publicSignals[2] !== expectedMerkleRoot) {
            return { valid: false, reason: 'Merkle root mismatch — wrong private key or unregistered identity' };
        }
        try {
            const ok = await snarkjs.groth16.verify(this.verificationKey, publicSignals, proof);
            return ok ? { valid: true } : { valid: false, reason: 'Groth16 verification failed' };
        } catch (err: any) {
            console.error('💥 groth16.verify error:', err?.message);
            console.error('   Stack:', err?.stack?.split('\n').slice(0, 4).join('\n   '));
            return { valid: false, reason: err?.message || 'Groth16 verification error' };
        }
    }

    /**
     * Role hash constants — must match ZKRoleGate.tsx and ROLE_HASHES in auth.ts
     */
    private static readonly ROLE_HASHES: Record<string, string> = {
        employee: '1000', manager: '1001', auditor: '1002', admin: '1003',
    };

    /**
     * Compute the ZK merkle root for a given private key and role hash using Poseidon.
     * Matches the computation in ZKRoleGate.tsx: computeMerkleRoot().
     */
    async computeMerkleRoot(zkPrivKey: string, roleHash: string): Promise<string> {
        const poseidon = await buildPoseidon();
        const F = poseidon.F;
        // Num2Bits(252) in the circuit requires privateKey < 2^252; % FIELD_SIZE can yield up to ~2^254
        const MAX_252 = BigInt(2) ** BigInt(252);
        const pkField = BigInt('0x' + zkPrivKey) % MAX_252;
        // publicAddress = Poseidon(pk, 0)
        const addr = F.toObject(poseidon([pkField, BigInt(0)]));
        // leaf = Poseidon(addr, roleHash, 1)
        const leaf = F.toObject(poseidon([addr, BigInt(roleHash), BigInt(1)]));
        // 8-level tree with all-zero siblings
        let node: bigint = leaf;
        for (let i = 0; i < 8; i++) {
            node = F.toObject(poseidon([node, BigInt(0)]));
        }
        return node.toString();
    }

    /**
     * Compute zkAddress = Poseidon(pk, 0) for a given ZK private key.
     */
    async computeZkAddress(zkPrivKey: string): Promise<string> {
        const poseidon = await buildPoseidon();
        const F = poseidon.F;
        const MAX_252 = BigInt(2) ** BigInt(252);
        const pkField = BigInt('0x' + zkPrivKey) % MAX_252;
        return F.toObject(poseidon([pkField, BigInt(0)])).toString();
    }

    /**
     * Generate a Groth16 role proof server-side and verify it.
     * Used when the wallet sends the ZK private key via the QR flow.
     *
     * Returns { valid, merkleRoot, reason? }
     */
    async generateAndVerifyRoleProof(
        zkPrivKey: string,
        requiredBadge: string,
        existingMerkleRoot?: string,
    ): Promise<{ valid: boolean; merkleRoot?: string; reason?: string }> {
        if (!this.isEnabled) {
            return { valid: false, reason: 'ZK-proof service not configured' };
        }

        const wasmPath = path.join(__dirname, '..', 'zkp', 'nftOwnership.wasm');
        const zkeyPath = path.join(__dirname, '..', 'zkp', 'nftOwnership_0001.zkey');

        if (!fs.existsSync(wasmPath) || !fs.existsSync(zkeyPath)) {
            return { valid: false, reason: 'Circuit artifacts missing from backend/src/zkp/ — copy nftOwnership.wasm and nftOwnership_0001.zkey there' };
        }

        const roleHash = ZKProofService.ROLE_HASHES[requiredBadge];
        if (!roleHash) {
            return { valid: false, reason: `Unknown badge: ${requiredBadge}` };
        }

        try {
            const t0 = Date.now();
            console.log(`\n${'═'.repeat(72)}`);
            console.log(`  ZK-PROOF AUTHENTICATION — Groth16 over BN128`);
            console.log(`${'═'.repeat(72)}`);
            console.log(`  Badge required : ${requiredBadge} (roleHash=${roleHash})`);
            console.log(`  Circuit        : nftOwnership.circom (Poseidon + 8-level Merkle)`);
            console.log(`  Proof system   : Groth16 (snarkjs)`);
            console.log(`  Curve          : BN128`);
            console.log(`  Public signals : 19 (1 output + 18 public inputs)`);
            console.log(`${'─'.repeat(72)}`);

            // Compute the expected merkle root from the private key
            const merkleRoot = await this.computeMerkleRoot(zkPrivKey, roleHash);
            console.log(`  [1/4] Merkle root computed    : ${merkleRoot.slice(0, 20)}…`);

            // If the caller provided an existing root, verify it matches
            if (existingMerkleRoot && existingMerkleRoot !== merkleRoot) {
                console.log(`  [ERR] Merkle root MISMATCH — expected ${existingMerkleRoot.slice(0, 20)}…`);
                console.log(`${'═'.repeat(72)}\n`);
                return { valid: false, reason: 'Merkle root mismatch — wrong private key for registered identity' };
            }
            if (existingMerkleRoot) {
                console.log(`        Matches registered root ✓`);
            }

            const MAX_252 = BigInt(2) ** BigInt(252);
            const pkField = (BigInt('0x' + zkPrivKey) % MAX_252).toString();

            const tProve0 = Date.now();
            console.log(`  [2/4] Generating Groth16 proof (witness + proving)…`);
            const { proof, publicSignals } = await snarkjs.groth16.fullProve(
                {
                    privateKey:         pkField,
                    nonce:              '0',
                    tokenId:            '1',
                    nftContractAddress: roleHash,
                    merkleRoot,
                    merkleProof:        Array(8).fill('0'),
                    merkleIndices:      Array(8).fill('0'),
                },
                wasmPath,
                zkeyPath,
            );
            const proveMs = Date.now() - tProve0;
            console.log(`        Proof generated in ${proveMs}ms`);
            console.log(`        π.a = [${proof.pi_a[0].slice(0, 16)}…, ${proof.pi_a[1].slice(0, 16)}…]`);
            console.log(`        π.b = [[${proof.pi_b[0][0].slice(0, 12)}…], [${proof.pi_b[1][0].slice(0, 12)}…]]`);
            console.log(`        π.c = [${proof.pi_c[0].slice(0, 16)}…, ${proof.pi_c[1].slice(0, 16)}…]`);

            console.log(`  [3/4] Verifying proof against verification key…`);
            console.log(`        isValid (signal[0])     : ${publicSignals[0]}`);
            console.log(`        roleHash (signal[1])    : ${publicSignals[1]}`);
            console.log(`        merkleRoot (signal[2])  : ${publicSignals[2].slice(0, 20)}…`);
            const tVerify0 = Date.now();
            const result = await this.verifyRoleProof(proof, publicSignals, roleHash, merkleRoot);
            const verifyMs = Date.now() - tVerify0;
            if (!result.valid) {
                console.log(`  [FAIL] Verification failed: ${result.reason}`);
                console.log(`${'═'.repeat(72)}\n`);
                return { valid: false, reason: result.reason };
            }

            const totalMs = Date.now() - t0;
            console.log(`        groth16.verify() = true  (${verifyMs}ms)`);
            console.log(`  [4/4] PROOF ACCEPTED`);
            console.log(`${'─'.repeat(72)}`);
            console.log(`  Timing: merkle=${Date.now() - t0 - proveMs - verifyMs}ms  prove=${proveMs}ms  verify=${verifyMs}ms  total=${totalMs}ms`);
            console.log(`${'═'.repeat(72)}\n`);
            return { valid: true, merkleRoot };
        } catch (err: any) {
            console.error('💥 generateAndVerifyRoleProof caught error:', err?.message);
            console.error('   Stack:', err?.stack?.split('\n').slice(0, 6).join('\n   '));
            return { valid: false, reason: err?.message || 'Proof generation error' };
        }
    }

    /**
     * Get verification service statistics
     * 
     * @returns Object containing service stats
     */
    getServiceStats(): any {
        return {
            service: 'ZK-Proof Verification Service',
            status: this.isEnabled ? 'active' : 'demo-mode',
            protocol: this.verificationKey?.protocol || 'demo',
            curve: this.verificationKey?.curve || 'demo',
            nftContract: this.CORPORATE_EXCELLENCE_CONTRACT,
            publicInputs: this.verificationKey?.nPublic || 0,
            enabled: this.isEnabled,
            features: [
                'Zero-knowledge NFT ownership verification',
                'Privacy-preserving authentication',
                'Anonymous premium access tokens',
                'Groth16 zk-SNARK verification',
                'Corporate Excellence 2025 NFT support'
            ],
            privacy: {
                walletAddressHidden: true,
                identityPreserving: true,
                zeroKnowledgeProofs: this.isEnabled,
                anonymousAccess: true
            },
            mode: this.isEnabled ? 'production' : 'demo'
        };
    }
}

export default ZKProofService;
