import { Router, Request, Response } from 'express';
import { analyzeTimeline, queryTimeline } from '../services/ai.service';

const router = Router();

/**
 * POST /api/ai/analyze-timeline
 *
 * Runs rule-based anomaly detection over recent auth events and returns
 * per-anomaly explanations + an overall summary generated by Gemini.
 *
 * Body (all optional):
 *   companyId     string  — scope analysis to a specific company
 *   verifierId    string  — scope analysis to a specific verifier
 *   windowMinutes number  — how far back to look (default 60, max 1440)
 */
router.post('/analyze-timeline', async (req: Request, res: Response) => {
  try {
    const { companyId, verifierId, windowMinutes } = req.body;

    if (windowMinutes !== undefined) {
      const wm = Number(windowMinutes);
      if (!Number.isInteger(wm) || wm < 1 || wm > 1440) {
        return res.status(400).json({
          error: 'windowMinutes must be an integer between 1 and 1440',
        });
      }
    }

    const result = await analyzeTimeline({
      companyId: companyId || undefined,
      verifierId: verifierId || undefined,
      windowMinutes: windowMinutes ? Number(windowMinutes) : undefined,
    });

    return res.json({ success: true, data: result });
  } catch (err: any) {
    console.error('[POST /api/ai/analyze-timeline]', err);
    return res.status(500).json({ error: 'Analysis failed', message: err.message });
  }
});

/**
 * POST /api/ai/query
 *
 * Accepts a natural-language question, uses Gemini to convert it into
 * AuthTimelineFilters, fetches matching events, and returns results
 * with a plain-English summary.
 *
 * Body:
 *   question  string (required, max 500 chars)
 *   context   { companyId?, verifierId? }  — server-side scope override
 */
router.post('/query', async (req: Request, res: Response) => {
  try {
    const { question, context } = req.body;

    if (!question || typeof question !== 'string' || question.trim().length === 0) {
      return res.status(400).json({
        error: 'question is required and must be a non-empty string',
      });
    }

    if (question.length > 500) {
      return res.status(400).json({
        error: 'question must be 500 characters or fewer',
      });
    }

    const result = await queryTimeline({ question: question.trim(), context });
    return res.json({ success: true, data: result });
  } catch (err: any) {
    console.error('[POST /api/ai/query]', err);
    return res.status(500).json({ error: 'Query failed', message: err.message });
  }
});

export default router;
